### ISSUE TITLE
ENOBUFS

### ISSUE THREAD

**Issue by owocean** [jayu/tcp-local-tunnel#6]
I am trying to keep a server alive, but am having difficulty due to the tunnel constantly collapsing on itself with a ENOBUFS error. I am also getting many logs in the console all saying "connected to remote" when I believe I should only be getting one. Is this intended? And why does the tunnel keep collapsing?

**Comment by jayu** [comment]
I didn't use this lib for a while, but I may try to help. I didn't see ENOBUFS error before. Can you share more information about your setup, environment, system you are using? Repo with a reproduction of the problem would work best 💯

**Comment by owocean** [comment]
I kindof ended up just making my own tunnel which ended up working. I don't have access to the machine right now, but it was a windows 8 pc connected via ethernet
