### ISSUE TITLE
Forward https

### ISSUE THREAD

**Issue by hfossli-agens** [jayu/tcp-local-tunnel#7]
Does this support forwarding https over the tunnel in such a way that the middleware doesn't decrypt the https?

**Comment by jayu** [comment]
Yes, it should work, I tried to use this module with a proxy server. 
HTTPS is HTTP encrypted with TLS, TLS sends data over TCP.
So theoretically it's possible. It depends on how you set up https server.
Also, check  remote port forwarding via SSH https://www.ssh.com/ssh/tunneling/example
